In [6]:
# Ensure project root is in sys.path for imports
import sys
import os
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

# 02 - Data Preprocessing
This notebook covers the full preprocessing pipeline: loading, cleaning, feature engineering, splitting, and saving processed data.

In [7]:
import pandas as pd
import numpy as np
from src.data.preprocess import load_data, clean_data, select_features, split_data, save_processed_data

RAW_PATH = '../data/raw/train.csv'
PROCESSED_DIR = '../data/processed/'

In [8]:
df = load_data(RAW_PATH)
df.head()

INFO:src.data.preprocess:Data loaded successfully with 1460 rows

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [9]:
df_clean = clean_data(df)
df_clean.info()

INFO:src.data.preprocess:Data cleaning completed

<class 'pandas.core.frame.DataFrame'>
Index: 1455 entries, 0 to 1459
Data columns (total 85 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1455 non-null   int64
 1   MSSubClass     1455 non-null   object
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1455 non-null   float64
 4   LotArea        1455 non-null   int64
 5   Street         1455 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1455 non-null   object
 8   LandContour    1455 non-null   object
 9   Utilities      1455 non-null   object
 10  LotConfig      1455 non-null   object
 11  LandSlope      1455 non-null   object
 12  Neighborhood   1455 non-null   object
 13  Condition1     1455 non-null   object
 14  Condition2     1455 non-null   object
 15  BldgType       1455 non-null   object
 16  HouseStyle     1455 non-null   object
 17  OverallQual    1455 non-null   int64
 18  OverallCond    1455 non-null   int64
 19  YearBuilt      1455 non-null   int64
 20  YearRemodAdd   1455 non-null   int64
 21  RoofStyle      1455 non-null   object
 22  RoofMatl       1455 non-null   object
 23  Exterior1st    1455 non-null   object
 24  Exterior2nd    1455 non-null   object
 25  MasVnrType     585 non-null    object
 26  MasVnrArea     1455 non-null   float64
 27  ExterQual      1455 non-null   object
 28  ExterCond      1455 non-null   object
 29  Foundation     1455 non-null   object
 30  BsmtQual       1418 non-null   object
 31  BsmtCond       1418 non-null   object
 32  BsmtExposure   1417 non-null   object
 33  BsmtFinType1   1418 non-null   object
 34  BsmtFinSF1     1455 non-null   int64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1455 non-null   int64
 37  BsmtUnfSF      1455 non-null   int64
 38  TotalBsmtSF    1455 non-null   int64
 39  Heating        1455 non-null   object
 40  HeatingQC      1455 non-null   object
 41  CentralAir     1455 non-null   object
 42  Electrical     1454 non-null   object
 43  1stFlrSF       1455 non-null   int64
 44  2ndFlrSF       1455 non-null   int64
 45  LowQualFinSF   1455 non-null   int64
 46  GrLivArea      1455 non-null   int64
 47  BsmtFullBath   1455 non-null   int64
 48  BsmtHalfBath   1455 non-null   int64
 49  FullBath       1455 non-null   int64
 50  HalfBath       1455 non-null   int64
 51  BedroomAbvGr   1455 non-null   int64
 52  KitchenAbvGr   1455 non-null   int64
 53  KitchenQual    1455 non-null   object
 54  TotRmsAbvGrd   1455 non-null   int64
 55  Functional     1455 non-null   object
 56  Fireplaces     1455 non-null   int64
 57  FireplaceQu    765 non-null    object
 58  GarageType     1374 non-null   object
 59  GarageYrBlt    1374 non-null   float64
 60  GarageFinish   1374 non-null   object
 61  GarageCars     1455 non-null   int64
 62  GarageArea     1455 non-null   int64
 63  GarageQual     1374 non-null   object
 64  GarageCond     1374 non-null   object
 65  PavedDrive     1455 non-null   object
 66  WoodDeckSF     1455 non-null   int64
 67  OpenPorchSF    1455 non-null   int64
 68  EnclosedPorch  1455 non-null   int64
 69  3SsnPorch      1455 non-null   int64
 70  ScreenPorch    1455 non-null   int64
 71  PoolArea       1455 non-null   int64
 72  PoolQC         5 non-null      object
 73  Fence          280 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1455 non-null   int64
 76  MoSold         1455 non-null   int64
 77  YrSold         1455 non-null   int64
 78  SaleType       1455 non-null   object
 79  SaleCondition  1455 non-null   object
 80  SalePrice      1455 non-null   int64
 81  TotalSF        1455 non-null   int64
 82  TotalBath      1455 non-null   float64
 83  Age            1455 non-null   int64
 84  IsRemodeled    1455 non-null   int64
dtypes: float64(4), int64(37), object(44)
memory usage: 977.6+ KB

In [10]:
X, y = select_features(df_clean)
X_train, X_test, y_train, y_test = split_data(X, y)
print('Train shape:', X_train.shape)
print('Test shape:', X_test.shape)

INFO:src.data.preprocess:Train shape: (1164, 8), Test shape: (291, 8)

Train shape: (1164, 8)
Test shape: (291, 8)

In [11]:
save_processed_data(pd.concat([X, y], axis=1), output_dir=PROCESSED_DIR)

INFO:src.data.preprocess:Saved processed data to ../data/processed//cleaned_20250731_1618.csv

'../data/processed//cleaned_20250731_1618.csv'

In [13]:
import sys, os
sys.path.append(os.path.abspath(".."))